name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Build with Maven
        run: mvn clean install

      - name: test
        run: mvn test

      - name: Publish Check
        uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Maven
          conclusion: ${{ job.status }}
          output: |
            {"summary v2":"${{ steps.test.outputs.summary }}"}